spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: "081123"
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080